services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    volumes:
      - "./mysql-data:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: welcome
      MYSQL_DATABASE: trainingdb
      MYSQL_USER: training
      MYSQL_PASSWORD: training

